### ISSUE TITLE
Weapons are invisible in first person.

### ISSUE THREAD

**Issue by Bar2co** [zhongjiedong/Tsukiro#79] opened 2022-01-22 15:30 UTC
### What happened?

Only bows show up.
And the dwarven gauntlets from book of uunp iron and steel are invisible too.
Base form: 490011F6
Ref Form:FF017D67
Also I recomend adding AddItemMenu because some items disapear into the void when we drop them

### Modlist version

1.1.694

**Comment by zhongjiedong** [comment] 2022-01-22 15:47
which weapons? Every single one? Did you make any changes to the modlist as I cannot reproduce

**Comment by Bar2co** [comment] 2022-01-22 17:04
I restarted after adding AddItemMenu to test more mods and it fixed it. I already tried restarting without any change and it didn't work. I don't know why. I didn't add a mod to the modpack

**Comment by Bar2co** [comment] 2022-01-22 17:04
Gauntlets are still invisible tho

**Comment by zhongjiedong** [comment] 2022-01-22 17:23
well adding additemmenu is adding mods to the pack, getting items from that is not supported. I will see about the gauntlets

**Comment by zhongjiedong** [comment] 2022-03-01 18:37
fixed in 1.1.72

**Closed by zhongjiedong** 2022-03-01 18:37 UTC
